# Generated by Django 4.0.6 on 2022-07-12 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_application_date_applied'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('contact_method', models.CharField(choices=[('P', 'Phone'), ('E', 'Email'), ('S', 'Social Media'), ('I', 'In-person'), ('O', 'Other')], default='P', max_length=1)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.application')),
            ],
        ),
    ]
