# Generated by Django 4.0.6 on 2022-07-12 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_contact_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_status', models.CharField(choices=[(0, 'Application Sent'), (1, 'Followed-Up'), (2, 'Received Contact'), (3, 'Interview Scheduled'), (4, 'Interview Finished'), (5, 'Offer Received'), (6, 'Offer Accepted'), (7, 'Application Closed')], default=(0, 'Application Sent'), max_length=30)),
                ('is_priority', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-date']},
        ),
    ]
