# Generated by Django 4.0.6 on 2022-07-12 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_status_alter_contact_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='application',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.application'),
            preserve_default=False,
        ),
    ]
