# Generated by Django 4.0.6 on 2022-07-12 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_status_application'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='application',
        ),
    ]
