# Generated by Django 4.0.6 on 2022-07-12 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_status_application'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='application',
        ),
        migrations.RemoveField(
            model_name='status',
            name='application_status',
        ),
        migrations.RemoveField(
            model_name='status',
            name='is_priority',
        ),
    ]
