# Generated by Django 4.0.6 on 2022-07-12 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_delete_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_status', models.CharField(choices=[(0, 'Application Sent'), (1, 'Followed-Up'), (2, 'Received Contact'), (3, 'Interview Scheduled'), (4, 'Interview Finished'), (5, 'Offer Received'), (6, 'Offer Accepted'), (7, 'Application Closed')], default=(0, 'Application Sent'), max_length=30)),
                ('is_priority', models.BooleanField(default=False)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.application')),
            ],
        ),
    ]
