# Generated by Django 4.0.6 on 2022-07-12 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='application_status',
            field=models.CharField(choices=[('A', 'Application Sent'), ('B', 'Followed-Up'), ('C', 'Received Contact'), ('D', 'Interview Scheduled'), ('E', 'Interview Finished'), ('F', 'Offer Received'), ('G', 'Offer Accepted'), ('H', 'Application Closed')], default=('A', 'Application Sent'), max_length=30),
        ),
    ]
