# Generated by Django 4.0.6 on 2022-07-12 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_alter_status_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='is_priority',
            field=models.CharField(choices=[('Y', 'Priority'), ('N', 'Not a Priority')], default=('N', 'Not a Priority'), max_length=30),
        ),
    ]
